version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/ruby:2.7.1-node
    environment:
      BUDLE_PATH: vendor/bundle

orbs:
  win: circleci/windows@2.4.0

commands:
  sayhello:
    steps:
      - run: echo "hello world(command)"

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - sayhello
