version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:lts

jobs:
  install-certificates:
    executor: default
    steps:
      - checkout
      - run: apt-get update; apt-get install -y ca-certificates
  install_deps:
    executor: default
    steps:
      - run: echo "install_deps"
  test_a:
    executor: default
    steps:
      - run: echo "test_a"
  test_b:
    executor: default
    steps:
      - run: echo "test_b"
  deploy:
    executor: default
    steps:
      - run: echo "deploy"
  deploy-stg:
    executor: default
    steps:
      - run: echo "deploy to stage"
  deploy-prd:
    executor: default
    steps:
      - run: echo "deploy to production"

workflows:
  version: 2
  build-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - install_deps
      - test_a:
          requires:
            - install_deps
      - test_b:
          requires:
            - install_deps
      - deploy:
          requires:
            - test_a
            - test_b
      - deploy-stg:
          filters:
            branches:
              only:
                - /^stage-.*/
          requires:
            - deploy
      - deploy-prd:
          filters:
            branches:
              only:
                - main
          requires:
            - deploy