executors:
  default:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

version: 2.1
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Install node modules
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  test_jest:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Jest tests
          command: npx jest --ci --maxWorkers=2

workflows:
  version: 2
  build_test:
    jobs:
      - setup
      - test_jest:
          requires:
            - setup
