executors:
  with_db:
    docker:
      - image: cimg/ruby:2.7.6
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/mysql:8.0.18-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: rails_app_test
        command: mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/repo

version: 2.1
jobs:
  setup_test_rspec:
    executor: with_db
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Waiting for MySQL
          command: |
            dockerize -wait tcp://${DB_HOST}:3306 -timeout 120s
      - run:
          name: Setup database
          command: bundle exec rake db:schema:load --trace
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_test:
    jobs:
      - setup_test_rspec