version: 2.1
jobs:
  install_deps:
    steps:
      - run: echo "install_deps"
  test_a:
    steps:
      - run: echo "test_a"
  test_b:
    steps:
      - run: echo "test_b"

workflows:
  version: 2
  workflow:
    jobs:
      - install_deps
      - test_a:
          requires:
            - install_deps
      - test_b:
          requires:
            - install_deps